### PR TITLE
Add engines to package.json

### PR DESCRIPTION
**Pull request by gabritto**
Require node >= 12.
I could try to require node >= 10.10, but then we run into [this issue](https://github.com/microsoft/TypeScript/issues/32333) and it seems too much trouble.
This also means having to update the minimum node version in dtslint, types-publisher and DT.

### CODE REVIEW

**Comment by sandersn** [comment]
I believe @domoritz [had some reason to support node 10 in dtslint, although I didn't ask at the time](https://github.com/microsoft/dtslint/pull/272) because I wasn't aware of any reason that node 12 was required. 
The issue you linked appears to do with the types (although I might have misread it). Is it possible just to update the types and leave the engine version alone?

@domoritz did you have a specific reason that dtslint needed to support node 10?

**Comment by domoritz** [comment]
Yes, I am working on https://github.com/vega/vega and we use this package to [test our typings](https://github.com/vega/vega/blob/master/packages/vega-typings/package.json#L18). Since Node 10 is not deprecated (https://nodejs.org/en/about/releases/), we need to support it. 

It would probably make sense to test node 10 in https://github.com/microsoft/dtslint/blob/master/.travis.yml to make sure that the minimum node version is actually supported.

**Comment by sandersn** [comment]
I installed `@types/node@10.17.16` and got dts-critic to compile on its own, at least. Was the compilation error in conjunction with dtslint?

**Comment by domoritz** [comment]
Is this a question for @gabritto?

**Comment by gabritto** [comment]
@domoritz do you need to support all Node 10 versions (e.g. 10.0.0)? Or is Node >= 10.17.0 enough?

**Comment by domoritz** [comment]
I think the latest node 10 version is enough. We use Travis so I’d like to support the version they use.

**Comment by domoritz** [comment]
I think you can also use node typings for node 12 and still support node 10 (and test it on the CI). At least it has worked well for us in Vega: https://github.com/vega/vega/blob/master/package.json.
